CREATE TABLE IF NOT EXISTS notes(
id serial NOT NULL UNIQUE,
title VARCHAR(255) NOT NULL,
content TEXT NOT NULL,
created_at TIMESTAMP without time zone DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP without time zone DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);